[build]
  command = "npm run build --prefix mini_project"
  publish = "mini_project/dist"
  functions = "backend"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose", "dotenv", "cors", "bcryptjs", "jsonwebtoken", "serverless-http"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/handler/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
